# Generated by Django 4.2 on 2026-03-01 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.CharField(default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='completion_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='dependent_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependents', to='app.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='email_notification_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='task',
            name='time_estimate',
            field=models.IntegerField(blank=True, help_text='Time estimate in minutes', null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='time_logged',
            field=models.IntegerField(default=0, help_text='Time spent in minutes'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('design', 'Design'), ('in_progress', 'In Progress'), ('review', 'Review'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='design', max_length=20),
        ),
    ]
