# Generated by Django 5.1.2 on 2024-10-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='correction',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='pull_request',
            field=models.TextField(null=True),
        ),
    ]
