# Generated by Django 5.1.2 on 2024-10-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_profile_address_profile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reason',
            field=models.TextField(null=True),
        ),
    ]
