# Generated by Django 4.2.6 on 2024-10-29 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0004_task_reason"),
    ]

    operations = [
        migrations.RenameField(
            model_name="permisison",
            old_name="granted",
            new_name="access",
        ),
        migrations.AddField(
            model_name="permisison",
            name="project",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.project"
            ),
        ),
        migrations.AddField(
            model_name="permisison",
            name="task",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.task"
            ),
        ),
        migrations.AlterField(
            model_name="permisison",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
