# Generated by Django 4.2.6 on 2024-10-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_granted_permisison_access_permisison_project_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="permisison",
            name="reason",
            field=models.TextField(null=True),
        ),
    ]
