# Generated by Django 4.2.6 on 2024-10-29 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_personaltask"),
    ]

    operations = [
        migrations.AddField(
            model_name="personaltask",
            name="project",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.project"
            ),
        ),
    ]
