# Generated by Django 5.1.2 on 2024-11-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(null=True),
        ),
    ]
