# Generated by Django 5.1.3 on 2024-11-10 16:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_lead_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
