# Generated by Django 5.1.2 on 2024-12-30 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_lead_updated_alter_project_updated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('request_count', models.IntegerField(default=0)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
